[workspace]
members = [
  "crates/font-mud",
  "crates/hearth-macros",
  "crates/hearth-cognito",
  "crates/hearth-core",
  "crates/hearth-guest",
  "crates/hearth-rpc",
  "crates/hearth-wasm",
]

[workspace.dependencies]
hearth-rpc = { path = "crates/hearth-rpc" }
hearth-wasm = { path = "crates/hearth-wasm" }
hearth-macros = { path = "crates/hearth-macros" }

[workspace.dependencies.remoc]
version = "0.10"
default-features = false
features = ["default-codec-bincode"]

[workspace.dependencies.serde]
version = "1"
features = ["derive"]
