[workspace]
members = [
  "crates/font-mud",
  "crates/hearth-client",
  "crates/hearth-ctl",
  "crates/hearth-cognito",
  "crates/hearth-core",
  "crates/hearth-guest",
  "crates/hearth-ipc",
  "crates/hearth-network",
  "crates/hearth-rpc",
  "crates/hearth-server",
  "crates/hearth-types",
  "crates/hearth-wasm",
]

[workspace.dependencies]
hearth-ipc = { path = "crates/hearth-ipc" }
hearth-network = { path = "crates/hearth-network" }
hearth-rpc = { path = "crates/hearth-rpc" }
hearth-types = { path = "crates/hearth-types" }
hearth-wasm = { path = "crates/hearth-wasm" }
tracing = "0.1.37"

[workspace.dependencies.remoc]
version = "0.10"
default-features = false
features = ["default-codec-bincode"]

[workspace.dependencies.serde]
version = "1"
features = ["derive"]
