[workspace]
resolver = "2"
members = [
  "crates/font-mud",
  "crates/hearth-client",
  "crates/hearth-ctl",
  "crates/hearth-cognito",
  "crates/hearth-core",
  "crates/hearth-ipc",
  "crates/hearth-macros",
  "crates/hearth-network",
  "crates/hearth-rend3",
  "crates/hearth-server",
  "crates/hearth-types",
  "crates/hearth-wasm",
  "crates/rend3-alacritty",
]

[workspace.dependencies]
bytemuck = "1.13"
hearth-cognito = { path = "crates/hearth-cognito" }
hearth-core = { path = "crates/hearth-core" }
hearth-ipc = { path = "crates/hearth-ipc" }
hearth-macros = { path = "crates/hearth-macros" }
hearth-network = { path = "crates/hearth-network" }
hearth-rend3 = { path = "crates/hearth-rend3" }
hearth-types = { path = "crates/hearth-types" }
hearth-wasm = { path = "crates/hearth-wasm" }
parking_lot = "0.12"
serde_json = "1"
tracing = "0.1.37"

[workspace.dependencies.serde]
version = "1"
features = ["derive"]
