[workspace]
members = [
  "crates/font-mud",
  "crates/hearth-cognito",
  "crates/hearth-core",
  "crates/hearth-guest",
  "crates/hearth-wasm",
]

[workspace.dependencies]
hearth-wasm = { path = "crates/hearth-wasm" }