[package]
name = "hearth-cognito"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "5.0.0"
hearth-rpc = { workspace = true }
hearth-wasm = { workspace = true }
hearth-macros = { workspace = true }