[workspace]
members = [
  "hearth-guest",
  "hearth-test-wasm",
]

[workspace.dependencies]
hearth-guest = { path = "hearth-guest" }
hearth-types = { path = "../../crates/hearth-types" }
serde_json = "1"
