[package]
name = "hearth-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version= "4", features = ["derive"] }
hearth-network = { workspace = true }
hearth-rpc = { workspace = true }
remoc = { workspace = true, features = ["full"] }
tokio = { version = "1.24", features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.16", features = ["fmt"] }
