[package]
name = "hearth-rend3"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.20"
hearth-core = { workspace = true }
rend3 = "0.3"
rend3-routine = "0.3"
tokio = { version = "1.24", features = ["sync"] }
wgpu = "^0.12"
