[package]
name = "hearth-core"
version = "0.1.0"
edition = "2021"

[dependencies]
hearth-ipc = { workspace = true }
hearth-rpc = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3.16", features = ["fmt"] }
