name: Kindling Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup target add wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2.2.0
      with:
        workspaces: "kindling -> kindling/target"
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-targets --manifest-path kindling/Cargo.toml --target wasm32-unknown-unknown
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: rustup target add wasm32-unknown-unknown
    - run: rustup component add clippy
    - uses: Swatinem/rust-cache@v2.2.0
      with:
        workspaces: "kindling -> kindling/target"
    - uses: clechasseur/rs-clippy-check@v3
      with:
        working-directory: "kindling"
        args: --all-targets --target wasm32-unknown-unknown
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        components: rustfmt
        override: true
    - uses: LoliGothick/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: kindling_rustfmt
        working-directory: "kindling"
        flags: --all
