name: Pull Request Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2.2.0
    - name: Build
      run: cargo build --workspace --verbose --all-features
    - name: Run tests
      run: cargo test --workspace --verbose --all-features
  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: Swatinem/rust-cache@v2.2.0
    - run: rustup component add clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
  rustfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: LoliGothick/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
